services:
  client:
    build:
      context: ./client/job-board
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3001:3000"
  postgres:
    image: postgres:18
    container_name: job_board_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=job_board
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./server/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
